INSERT INTO notification_templates (
    template_id, name, event_type, body_template, created_at, updated_at
)
VALUES (
    'user-registration-template',
    'User Registration Email',
    'UserRegistered',
    '<!DOCTYPE html>\n<html xmlns:th=\"http://www.thymeleaf.org\">\n<head>\n    <meta charset=\"UTF-8\">\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n    <title>Welcome to TELUS</title>\n    <style>\n        body { font-family: Arial, sans-serif; line-height: 1.6; color: #333333; margin: 0; padding: 0; }\n        .container { max-width: 600px; margin: 0 auto; padding: 20px; }\n        .header { background-color: #4B286D; padding: 20px; text-align: center; }\n        .header img { max-width: 150px; }\n        .content { padding: 20px; background-color: #ffffff; }\n        .footer { background-color: #f4f4f4; padding: 20px; text-align: center; font-size: 12px; }\n        .button { display: inline-block; padding: 10px 20px; background-color: #66CC00; color: #ffffff; text-decoration: none; border-radius: 5px; margin: 20px 0; }\n    </style>\n</head>\n<body>\n    <div class=\"container\">\n        <div class=\"header\">\n            <img src=\"cid:telus-logo\" alt=\"TELUS Logo\">\n        </div>\n        <div class=\"content\">\n            <h2>Welcome to TELUS!</h2>\n            <p>Dear <span th:text=\"${userName}\">John Doe</span>,</p>\n            <p>Thank you for registering with TELUS. We''re excited to have you on board!</p>\n            <p>Your account has been successfully created with the following details:</p>\n            <ul>\n                <li>Username: <span th:text=\"${userName}\">John Doe</span></li>\n                <li>Email: <span th:text=\"${email}\">john.doe@example.com</span></li>\n            </ul>\n            <p>What''s Next?</p>\n            <ul>\n                <li>Complete your profile</li>\n                <li>Explore our services</li>\n                <li>Contact support if you need assistance</li>\n            </ul>\n            <a th:href=\"${loginUrl}\" class=\"button\">Login to Your Account</a>\n            <p>If you have any questions or need assistance, please don''t hesitate to contact our support team.</p>\n            <p>Best regards,<br>The TELUS Team</p>\n        </div>\n        <div class=\"footer\">\n            <p>This email was sent to <span th:text=\"${email}\">john.doe@example.com</span>. Please do not reply to this email.</p>\n            <p>&copy; <span th:text=\"${currentYear}\">2025</span> TELUS. All rights reserved.</p>\n        </div>\n    </div>\n</body>\n</html>',
    NOW(),
    NOW()
);
